name: Run Markov Chain Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy packaging networkx scikit-fuzzy yfinance pandas matplotlib

      - name: Run simulation in backtest mode for NVDa
        run: |
          python main.py --mode backtest --ticker NVDA 

      - name: Run simulation in backtest mode for MULN
        run: |
          python main.py --mode backtest --ticker MULN

      - name: Run simulation in backtest mode for TSLA
        run: |
          python main.py --mode backtest --ticker TSLA 

      - name: Run simulation in forecast mode for AAPL
        run: |
          python main.py --mode forecast --ticker AAPL